### ISSUE TITLE
How to debug in Intellij

### ISSUE THREAD

**Issue by altuga** [cescoffier/my-vertx-first-app#11]
Hello, 

I want to debug this app but I couldn't figure it out.
In README it says
**java -jar target/my-first-app-1.0-SNAPSHOT-fat.jar** which is a good but I want to debug in IntelliJ. Any idea?

Thanks.

**Comment by cescoffier** [comment]
Just create a "run" configuration in your IDE with:

- main-class set to `io.vertx.core.Launcher`
- application parameter set to `run f.q.n.MyFirstVerticle` (replace by the right package name)

Then, run it as debug....

**Comment by altuga** [comment]
It works ! Thanks.

**Comment by anindyam** [comment]
How do I debug a vertx verticle that has a main method for configurations and other things in the verticle itself ?

We generally invoke the jar and from the main method we deploy the first verticle.

If we use the vertx Launcher as the main class then it calls the start method directly and we are losing the configurations which are passed from the command line. 

Could you please suggest any workaround to this problem ?

**Comment by cescoffier** [comment]
Just create a second main class replying the verticle you want to deploy, and run this main in debug mode.

**Comment by anindyam** [comment]
Thanks for your reply but I am not sure I quite got you.

What I have is as shown below :

`public class CepApi extends AbstractVerticle {

    private static Logger log = LoggerFactory.getLogger(CepApi.class);

    public static final String CHANNEL_FACTORY_PATH = "/cep/1.0/channelFactory";
    public static final String CHANNEL_PATH_BASE = "/cep/1.0/channel/";
    public static final String EVENTCAMPAIGNLIST_PATH_BASE = "/cep/1.0/eventCampaignList/";

    private static final String CONFIG_FILE_NAME = CepApiConfig.CONFIG_FILE_NAME;

    public static CepApiConfig config;
    public static KineticaJdbcConnectionPoolManager KINETICA_JDBC_CONNECTION_POOL_MANAGER;

    private static Vertx vertxObj = null;
    private static WorkerExecutor executor = null;
    private static String configFileName;

    private KineticaTableWatcher watcher;
    private CampaignQuotaWatcher campaignQuotawatcher;

    private static int BATCH_SIZE_TO_HANDLE = 0;
    private static int DEFAULT_API_TIMEOUT_SEC = 55;
    private static String EVENT_TYPE;
    private static Boolean testModeParam = false;

    // ------------------------------------------------------------------------------
    // Launcher
    // ------------------------------------------------------------------------------

    public static void main(String[] args) {

        log.info("Initialising, logging using: " + LoggerFactory.getILoggerFactory().getClass().getCanonicalName());

        try {
            //ProcData procData = ProcData.get();
            //Map<String, String> params = procData.getParams();
            //testModeParam = Boolean.parseBoolean(params.get("testMode"));
        } catch (RuntimeException e) {
            log.warn("Running outside of UDF - params may not be set correctly");
        }

        //Handle command line arguments
        ArgumentParser argumentParser = ArgumentParsers.newFor("CepApi").build().defaultHelp(true)
                .description("Parse command line arguments ...");
        argumentParser.addArgument("-d", "--config-root-dir")
                .dest("configDir")
                .setDefault("./config/cep-api")
                .help("Specify the config root directory");

        Namespace ns = null;
        try {
            ns = argumentParser.parseArgs(args);
            configFileName = ns.getString("configDir") + File.separator + CONFIG_FILE_NAME;
            config = CepApiConfig.getConf(configFileName);
            KINETICA_JDBC_CONNECTION_POOL_MANAGER = KineticaJdbcConnectionPoolManager.getConnectionPoolManager(config.getGpuDbConfig());
            BATCH_SIZE_TO_HANDLE = config.getEventBatchSize();
            EVENT_TYPE = config.getEventType();
            DEFAULT_API_TIMEOUT_SEC = config.getDefaultApiTimeoutSec();
        } catch (ArgumentParserException ape) {
            argumentParser.handleError(ape);
            System.exit(-1);
        }
        /* With vertx 3.6.3 this gave a runetime error...TBD
        Vertx vertx = Vertx.vertx(new VertxOptions().setMetricsOptions(
        		new DropwizardMetricsOptions().setEnabled(true).
                setJmxEnabled(true).
                setJmxDomain("lippo_cep")
        		));
        */
        VertxOptions options = new VertxOptions();
        options.setMaxEventLoopExecuteTime(Long.MAX_VALUE);

        if (config.getAppMonitoringConfig().getBoolean("enabled")) {
            options.setMetricsOptions(
                    new MicrometerMetricsOptions()
                            .setPrometheusOptions(new VertxPrometheusOptions().setEnabled(true))
                            .setEnabled(true));
        }

        Vertx vertx = Vertx.vertx(options);
        vertx.deployVerticle(new CepApi());

        final Config vertxConfig = config.getAppVertxConfig();
        final int poolSize = vertxConfig.getInt("worker-pool-size");
        final long maxExecuteTimeSeconds = vertxConfig.getLong("worker-max-exec-time-seconds");

        executor = vertx.createSharedWorkerExecutor("cep-rule-worker-pool", poolSize, maxExecuteTimeSeconds, TimeUnit.SECONDS);
    }


    // ------------------------------------------------------------------------------
    // Vertx
    // ------------------------------------------------------------------------------

    /**
     * Getter for property 'vertxObj'.
     *
     * @return Value for property 'vertxObj'.
     */
    public static Vertx getVertxObj() {
        return vertxObj;
    }

    @Override
    public void stop() throws Exception {
        super.stop();
        watcher.shutDown();
        campaignQuotawatcher.shutDown();
    }

    @Override
    public void start() throws Exception {

        log.info("Starting with testMode: " + Boolean.toString(testModeParam));
        vertxObj = vertx;

        Router router = Router.router(vertx);

        router.route().handler(BodyHandler.create());
        router.get(ApiUri.V1_DEFAULT).handler(this::handleGetAlive);

        router.post(ApiUri.V1_RULES_EVAL).handler(this::handlePostEvalRules); // send a list of events to be evaluated against rules.
        router.post(ApiUri.V1_RULES_UPDATE).handler(this::handleUpdateRules);

        router.post(ApiUri.V2_RULES_EVAL).handler(this::handlePostEvalRulesAsync);
        router.post(ApiUri.V2_RULES_UPDATE).handler(this::handleUpdateRules);
        router.post(ApiUri.V2_CAMPAIGN_RELOAD).handler(this::handleCampaignReload);
        router.post(ApiUri.V2_CAMPAIGN_STATE_UPDATE).handler(this::handleCampaignStateUpdate);
        router.post(ApiUri.V2_MERGE_DATASET).handler(this::handleDatasetMerge);

        router.post(ApiUri.V2_RULES_EVAL_SYNC).blockingHandler(this::handlePostEvalRulesSync);

        final Config monitoringConfig = config.getAppMonitoringConfig();
        if (monitoringConfig.getBoolean("enabled")) {
            router.route(monitoringConfig.getString("metrics-uri")).handler(PrometheusScrapingHandler.create());
        }
        vertx.createHttpServer().requestHandler(router).listen(Integer.parseInt(config.getRestServerPort()));
// Start other verticles

`

**Comment by anindyam** [comment]
Because the main method is not invoked the line:

`final Config monitoringConfig = config.getAppMonitoringConfig();`

throws NPE
