### ISSUE TITLE
jquery版本与boostrap版本不匹配bug

### ISSUE THREAD

**Issue by okou19900722** [cescoffier/my-vertx-first-app#4]
在看你的教程学习中，但是你的jquery版本与bootstrap版本不同，而且你这个版本的bootstrap好像还有一个依赖没有加，所以点击 Add a new bottle 按钮不会弹框。我找到原英文版本的代码，根据他的版本改了之后就正常了

**Comment by cescoffier** [comment]
Sorry, but my Chinese skills are not really good... Could you translate it in English ?

**Comment by cescoffier** [comment]
That's the google translate version:

```
In the course of your study, but your version of jquery and bootstrap different versions, and you have this version of the bootstrap seems to have no dependence on Canada, so click Add a new bottle button will not bomb box. I found the original English version of the code, according to his version changed after the normal
```

(Canada ???)

**Comment by okou19900722** [comment]
@cescoffier I am sorry, but something was wrong. I was read another version with chinese from https://github.com/quanke/vertx3_study_demo. it's a translate version from your blog. so I write a wrong Issues. my english is bad, i am sorry to make you read hard

**Comment by Champal** [comment]
Hi,
I don't speak Chinese but there is a bug with the `Add button` and `Bootstrap`
If the browser width is small we can't click on the `Add button`
This is because the `h1` and `button ` are outside the `row/col `
```
<h1>My Whiskies</h1>
<button class="pull-right btn btn-primary product-add" data-action="add" data-toggle="modal"
                data-target="#productModal">
            <span class="glyphicon glyphicon-plus"></span> Add a new bottle
        </button>
<div class="row">
  <div class="col-md-12">
```
This work with all width : 
```
<div class="row">
  <div class="col-md-12">
     <h1>My Whiskies</h1>
      <button class="pull-right btn btn-primary product-add" data-action="add" data-toggle="modal"
                data-target="#productModal">
            <span class="glyphicon glyphicon-plus"></span> Add a new bottle
      </button>
```
